### ISSUE TITLE
BLAS support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/mumps-feedstock#1]
Need to update with BLAS stuff we should be following [these guidelines]( https://conda-forge.hackpad.com/BLAS-Numpy-Friends-86De62hoNdT ). Can also look at NumPy and SciPy for examples. Also please remember to create the PR from a branch on your fork.

xref: https://github.com/conda-forge/staged-recipes/pull/1445#issuecomment-255785333

**Comment by basnijholt** [comment]
I have opened #2 which is similar to the `numpy` recipe. Is this what you meant?

**Comment by basnijholt** [comment]
Closed by 8c56823.
