### ISSUE TITLE
pkgconfig

### ISSUE THREAD

**Issue by jcapriot** [conda-forge/mumps-feedstock#104]
### Comment:

I would like to put in a request for installed pkgconfig files for the installed mumps. I don't imagine that the source code generates anything, but you could create some simple files for the libraries installed during the conda-forge building steps. As a simple example:

```
prefix= <-WRITE $PREFIX TO HERE DURING BUILD
exec_prefix=${prefix}
libdir=${prefix}/lib
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: dmumps_seq
Description: The sequential double MUMPS library
Version: <- WRITE THE VERSION STRING TO HERE DURING BUILD
Cflags: -I${includedir}
Libs: -L${libdir} -ldmumps_seq
```

I also do not know what this would correspond to on windows machines.

**Comment by akhmerov** [comment]
:+1: from me. This wouldn't help if the library is provided not via conda-forge, but would greatly simplify conda-forge-based linking. I've given a shot to write a wrapper that uses meson-python for builds , and my solution so far [is not pretty](https://gitlab.kwant-project.org/kwant/mumpy/-/blob/3fe6efcbe886d61c31cc6f4282fbd5f63ab2c374/meson.build#L39-60).

**Comment by minrk** [comment]
@akhmerov I added these in #109. Could you check if they would work for you? I did them for the regular mumps libs, but not mumps_common or pord (it's unclear to me if users need to link those libs directly, since they are linked from the public-facing mumps libs).
