### ISSUE TITLE
Compile mumps as a shared library

### ISSUE THREAD

**Issue by jbweston** [conda-forge/mumps-feedstock#13]
Currently, this recipe builds mumps as a static library. As such, it contains
undefined symbols that are supposed to be found in the libraries that mumps
depends on (e.g. scotch).

The problem with this is that whenever we want to link against mumps we also have to link against all the dependencies of mumps as well (see e.g. [this thread](https://gitlab.kwant-project.org/kwant/kwant/merge_requests/77)). This is clearly not great.

Debian already builds a mumps as a shared library, and as far as I can tell it is just a case of applying a few patches to the makefiles to add extra targets that correctly invoke the compiler to build shared libs.

I think that it may just be a case of taking over these patches from the Debian packaging (available [over here](https://packages.debian.org/jessie/libmumps-scotch-4.10.0)) and massaging them slightly (e.g. to template out the library version).

**Comment by jbweston** [comment]
The same treatment should also be applied to dependencies that are also currently built as static libs (scotch).

**Comment by minrk** [comment]
I tried to apply/adapt the debian patches, but they have a bit of debian-specific-ness in them, and logically enough don't build shared libs on mac. But they should serve as a reference, at least, and show that it should be a relatively simple patch to add the shared lib targets as well. Given the dependency chain, I think it may make sense to do scotch first, then mumps.
