### ISSUE TITLE
build with MPI

### ISSUE THREAD

**Issue by minrk** [conda-forge/mumps-feedstock#14]
People need MUMPS built with MPI for use in PETSc, and I'm trying to figure out the best way to go about it. Would it be possible for this recipe to be built with MPI? Or should that be done as a separate `mumps-mpi` package? Is there a downside to having built with MPI when running in serial?

If it should be a separate package that can be done on this repo in a branch (as is done with scotch/pt-scotch), or a new feedstock. Preferences?

cf https://github.com/conda-forge/petsc-feedstock/issues/12

**Comment by basnijholt** [comment]
> Is there a downside to having built with MPI when running in serial?

@michaelwimmer you might be able to answer this question (and probably also the others).

**Comment by minrk** [comment]
After [submitting scalapack](https://github.com/conda-forge/staged-recipes/pull/2609), I was able to build parallel mumps (I think) with scalapack and ptscotch locally on Linux and macOS. So I have the recipe, I just need somewhere to put it.

**Comment by garth-wells** [comment]
Any updates on this?

**Comment by minrk** [comment]
#16 works, just needs a decision as to whether it should be a separate branch / package or replace the existing package. If mumps should support parallel by default, then I think #16 can be merged as-is.

**Comment by basnijholt** [comment]
I think it can be merged. I discussed it with people that have more knowledge about the implications than I have, and they said it should not lead to any issues.
