### ISSUE TITLE
mumps and mumps-mpi cannot be installed side-by-side

### ISSUE THREAD

**Issue by michaelwimmer** [conda-forge/mumps-feedstock#34]
Issue:

Both the sequential version and the mpi version install libraries with the same name, e.g. libdmumps.a. If both versions are installed, the later installed versions overwrites the other one.

Since the mumps libraries are static, this does not affect other conda packages at this point, as they will be already linked statically to the right version at installation time. However, if you want to use them directly in your code, this is a problem.

I would suggest to use different names for the two versions, like Debian does (see https://tracker.debian.org/pkg/mumps and related pages).

**Comment by michaelwimmer** [comment]
> BTW, @michaelwimmer how did you encounter this? I haven't seen folks running both parallel and seq mumps at the same time before.

Both mumps-mpi (used by e.g. petsc4py) as well as mumps (used by kwant) were installed as dependencies on my system. I then tried to link a C-program by hand to the conda installed mumps and then found out that only (in my case, would depend on installation order) the mpi libraries were present.

Actually, given that both mumps and mumps-mpi are static libraries, none of these packages would actually *require* mumps/mumps-mpi to be installed during runtime. But once those would be turned into shared libs, there would be a serious problem.

**Comment by jbweston** [comment]
> Both the sequential version and the mpi version install libraries with the same name, e.g. libdmumps.a. If both versions are installed, the later installed versions overwrites the other one.

I would expect this to be a thing that it should know about and would refuse to install the second package because of the conflict. Isn't this one of the killer features of a package manager; that you can't break your system in this way?

**Comment by minrk** [comment]
Any opinions on which path to take for resolving the conflict? I can have a look at 4. unless folks have other opinions.

**Comment by minrk** [comment]
Option 4 is now implemented in #36, creating a new `mumps-seq` package that differs from the current serial `mumps`:

- sequential mumps libraries now have a `_seq` suffix
- libseq mpi headers are in `include/mumps_seq` with their original names, instead of being in `include` with a modified `mumps_` name.
