### ISSUE TITLE
Only one variant of mumps-mpi is created

### ISSUE THREAD

**Issue by isuruf** [conda-forge/mumps-feedstock#43]
See https://anaconda.org/conda-forge/mumps-mpi/files.

This is due to the mumps-mpi package having the same hash for the two variants.

**Comment by isuruf** [comment]
@minrk, any ideas how to fix this?

**Comment by minrk** [comment]
That's strange. Looking into it now. The two builds have different host dependencies, so they shouldn't have the same hash.

I need to figure out how conda_build computes the hash, since it's getting the wrong inputs.

**Comment by minrk** [comment]
I've found the first culprit: inspecting the hash computation shows that mumps-mpi is actually using the contents of mumps-seq to compute hash inputs, so it excludes `mpi` from used_vars. Not sure exactly why that's happening.

**Comment by minrk** [comment]
I tracked it down. conda_build gets super confused when the *existance* of outputs is gated by conditionals, which this recipe does. Replacing those conditionals with `build.skip = True` seems to fix it. PR on its way.

**Comment by isuruf** [comment]
Thanks @minrk
