### ISSUE TITLE
Support for newer versions?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/mumps-feedstock#83]
### Comment:

Mumps is currently at version 5.5.1, but version 5.2.1 is the latest version available from conda-forge.  Would it be possible to update to a more recent version?

**Comment by DManowitz** [comment]
Note, however, that v5.5.1 switches to 64-bit integers, so it may introduce compatibility problems with other packages that depend on it.  Thus, it would probably be good to at least have v5.5.0.

**Comment by minrk** [comment]
it looks like much of our patches can be dropped due to mumps itself supporting shared library builds.

I don't know how to maintain the Windows builds, hopefully they don't really need to be touched
